package myworld.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.boot.autoconfigure.domain.EntityScan;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

// TODO: https://www.baeldung.com/spring-data-dynamodb
@DynamoDBTable(tableName = "books-master") // TODO: replace with books-XXX from properties
public class Book implements Serializable {
	private static final long serialVersionUID = 1L;

	private String id;
	private String isbn;
	private String title;
	private String series;
	private int number;

	public Book(String isbn, String title) {
		this.isbn = isbn;
		this.title = title;
	}
	
	public Book() {}

	@Id
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	@DynamoDBAttribute
	public String getIsbn() {
		return isbn;
	}

	@DynamoDBAttribute
	public String getTitle() {
		return title;
	}
	
	@DynamoDBAttribute
	public String getSeries() {
		return series;
	}

	@DynamoDBAttribute
	public int getNumber() {
		return number;
	}

	public void setId(String id) {
		this.id = id;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public void setSeries(String series) {
		this.series = series;
	}

	public void setNumber(int number) {
		this.number = number;
	}

}
